#!/bin/bash
docker run \
    --rm \
    --name plex \
    -d \
    -v /etc/localtime:/etc/localtime \
    -v /plex/media/movies:/plex/media/movies \
    -v /plex/media/series:/plex/media/series \
    -v /plex/config/codecs:/plex/config/Codecs \
    -v /plex/config/plug-in-support:/plex/config/Plug-in\ Support \
    -v /plex/config/plug-ins:/plex/config/Plug-ins \
    -v /plex/config/preferences.xml:/plex/config/Preferences.xml \
    -v /var/log/plex:/plex/logs \
    -v /var/backups/plex:/plex/backups \
    -e PLEX_CLAIM="<claimToken>" \
    -e ADVERTISE_IP="http://<hostIPAddress>:32400/" \
    -p 32400:32400 \
    -p 1900:1900 \
    -p 3005:3005 \
    -p 5353:5353 \
    -p 8324:8324 \
    -p 32410:32410 \
    -p 32412:32412 \
    -p 32413:32413 \
    -p 32414:32414 \
    -p 32469:32469 \
        plex
