#!/bin/bash
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

trap /plex/scripts/containerShutdown HUP SIGHUP INT SIGINT QUIT SIGQUIT TERM SIGTERM

/plex/scripts/utilSetExtension XBMCnfoMoviesImporter
/plex/scripts/utilSetExtension XBMCnfoTVImporter

source /plex/scripts/containerConfig
$startWebCmd & $startDummyCmd
eval $waitDummyCmd
