#!/bin/bash
startWebCmd="/plex/scripts/webStartup"
stopWebCmd="/plex/scripts/webShutdown"
stopVpnCmd="/plex/scripts/vpnShutdown"
startDummyCmd="/plex/scripts/containerDummy"
waitDummyCmd="ps axf | grep containerDummy | grep -v grep | awk '{print \"wait \" \$1}' | sh"
stopDummyCmd="ps axf | grep containerDummy | grep -v grep | awk '{print \"kill -9 \" \$1}' | sh"
