#!/bin/bash
/plex/scripts/utilSetExtension XBMCnfoMoviesImporter
/plex/scripts/utilSetExtension XBMCnfoTVImporter

trap /plex/scripts/containerShutdown HUP SIGHUP INT SIGINT QUIT SIGQUIT TERM SIGTERM

source /plex/scripts/containerConfig
$startWebCmd & $startDummyCmd
eval $waitDummyCmd
