#!/bin/bash

FILE_NAME_EXCLUDES=/plex/config/Script\ Data/fileNameExcludes
FILE_CONTENT_EXCLUDES=/plex/config/Script\ Data/fileContentExcludes

checkFileNames() {
    if [ -f "$FILE_NAME_EXCLUDES" ];
    then
        echo "Check for wrong file names"
        while read -r LINE
        do
            if [[ "$LINE" == "" ]];
            then
                continue
            fi
            if [[ "$LINE" =~ ^#.* ]];
            then
                continue
            fi
            echo "Check for $LINE"
            find $1 -name "$LINE"
        done < "$FILE_NAME_EXCLUDES"
    fi
}

checkFileContents() {
    if [ -f "$FILE_CONTENT_EXCLUDES" ];
    then
        echo "Check for wrong file contents"
        while read -r LINE
        do
            if [[ "$LINE" == "" ]];
            then
                continue
            fi
            if [[ "$LINE" =~ ^#.* ]];
            then
                continue
            fi
            echo "Check for $LINE"
            grep --include=\*.nfo -ril $1 -e "$LINE"
        done < "$FILE_CONTENT_EXCLUDES"
    fi
}

case $1 in
    media)
        checkFileNames "/plex/media"
        checkFileContents "/plex/media"
        ;;
    upload)
        checkFileNames "/plex/upload"
        checkFileContents "/plex/upload"
        ;;
    *)
        echo "Usage: $0 (media | upload)"
        ;;
esac
