#!/bin/bash

setMediaPermit() {
    sudo chown -R $RUN_USER:$RUN_GROUP /plex/media
    find /plex/media -type d -exec chmod 755 {} \;
    find /plex/media -type f -exec chmod 644 {} \;
}

setUploadPermit() {
    sudo chown -R $RUN_USER:$RUN_GROUP /plex/upload
    find /plex/upload -type d -exec chmod 755 {} \;
    find /plex/upload -type f -exec chmod 644 {} \;
    chmod 777 /plex/upload
}

case $1 in
    media)
        setMediaPermit
        ;;
    upload)
        setUploadPermit
        ;;
    *)
        echo "Usage: $0 (media | upload)"
        ;;
esac
