#!/bin/bash

FILE_NAME_EXCLUDES=/plex/config/Plug-in\ Support/fileNameExcludes
FILE_CONTENT_EXCLUDES=/plex/config/Plug-in\ Support/fileContentExcludes

checkFileNames() {
    if [ -f "$FILE_NAME_EXCLUDES" ];
    then
        while read -r LINE
        do
            if [ "$LINE" != "" ] && [ "$LINE" != #* ];
            then
                find $1 -name "$LINE"
            fi
        done < "$FILE_NAME_EXCLUDES"
    end
}

checkFileContents() {
    if [ -f "$FILE_CONTENT_EXCLUDES" ];
    then
        while read -r LINE
        do
            if [ "$LINE" != "" ] && [ "$LINE" != #* ];
            then
                grep --include=\*.nfo -ril $1 -e "$LINE"
            fi
        done < "$FILE_CONTENT_EXCLUDES"
    end
}

case $1 in
    media)
        checkFileNames "/plex/media"
        checkFileContents "/plex/media"
        ;;
    upload)
        checkFileNames "/plex/upload"
        checkFileContents "/plex/upload"
        ;;
    *)
        echo "Usage: $0 (media | upload)"
        ;;
esac
