#!/bin/bash

setPermit() {
    sudo chown -R $RUN_USER:$RUN_GROUP $1
    find $1 -type d -exec chmod 755 {} \;
    find $1 -type f -exec chmod 644 {} \;
}

case $1 in
    media)
        setPermit "/plex/media"
        ;;
    upload)
        setPermit "/plex/upload"
        ;;
    *)
        echo "Usage: $0 (media | upload)"
        ;;
esac
