#!/bin/bash
LC_ALL=en_US.UTF-8
LANG=en_US.UTF-8
PLEX_MEDIA_SERVER_INFO_MODEL=$(uname -m)
PLEX_MEDIA_SERVER_INFO_PLATFORM_VERSION=$(uname -r)
startServerCmd="/usr/lib/plexmediaserver/Plex Media Server"
"$startServerCmd"
